In [12]:
import numpy as np

In [13]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[1]

1

In [15]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [16]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [17]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [18]:
slice_of_arr = arr[:6]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [23]:
arr_cpy = arr.copy()

In [25]:
arr_cpy[:6] = 0

In [26]:
arr_cpy

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

# indexing on 2d array

In [32]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[1]

array([20, 25, 30])

In [34]:
arr_2d[1][1]

25

In [35]:
arr_2d[2,2]

45

In [36]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
bool_arr = arr < 4
bool_arr

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [43]:
arr[bool_arr]

array([1, 2, 3])

In [44]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
type(bool_arr)

numpy.ndarray

In [47]:
type(arr)

numpy.ndarray

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [51]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [53]:
np.sqrt(6)

2.449489742783178

In [54]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [55]:
arr.sum()

55

In [56]:
arr.mean()

5.5

In [57]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d.shape

(3, 4)

In [58]:
arr_2d.sum()

78

In [ ]:
arr_2d.sum(axis=0)
#sum of columns

array([15, 18, 21, 24])

In [60]:
#sum of rows
arr_2d.sum(axis=1)


array([10, 26, 42])