In [12]:
import numpy as np

In [13]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[1]

1

In [15]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [16]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [17]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [18]:
slice_of_arr = arr[:6]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [23]:
arr_cpy = arr.copy()

In [25]:
arr_cpy[:6] = 0

In [26]:
arr_cpy

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

# indexing on 2d array

In [32]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[1]

array([20, 25, 30])

In [34]:
arr_2d[1][1]

25

In [35]:
arr_2d[2,2]

45

In [36]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
bool_arr = arr < 4
bool_arr

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [43]:
arr[bool_arr]

array([1, 2, 3])

In [44]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
type(bool_arr)

numpy.ndarray

In [46]:
type(arr)

numpy.ndarray