In [1]:
import numpy as np

In [2]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
myMatrix = np.array(mylist)

In [4]:
myMatrix.shape

(3, 3)

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.zeros((4,10))+10 *4/100

array([[0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]])

In [11]:
np.linspace(1,100,10) #start, stop, numbers

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(4,5) *20

array([[11.66058005, 14.29301136,  2.33572396,  2.67042356, 14.54236306],
       [ 5.28354118,  6.16033229, 12.54046206,  7.69808552, 16.55814798],
       [ 6.27694783,  0.85226459,  2.73499713,  8.31696753,  6.97955278],
       [ 4.3329298 ,  7.03746283, 10.6808156 ,  1.59864994, 18.50453561]])

In [ ]:
np.random.randn(5,5) #can be negetive

array([[ 1.18489181, -0.41703913, -1.1244383 ,  0.28851892, -0.53620304],
       [-0.04162606,  1.30352781,  1.59486057,  0.65912569, -0.01372979],
       [-1.13124247,  1.75511911, -0.23922429, -2.14363858,  0.47013691],
       [ 1.05337426,  0.48943457,  0.47951605, -0.88655446, -1.62591807],
       [ 2.40805566, -0.12991687,  0.02417771,  1.03721327, -0.08183366]])

In [28]:
np.random.randint(1,100,10)

array([ 4, 20, 80, 41, 54, 45, 87,  9, 51, 69])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
randArr = np.random.randint(0,50,10)
randArr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
randArr.max()

43

In [37]:
randArr.min()

1

In [38]:
randArr.argmax() #index

3

In [39]:
randArr.argmin()

1

In [41]:
randArr.dtype

dtype('int32')