In [42]:
import numpy as np

In [43]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [44]:
myMatrix = np.array(mylist)

In [45]:
myMatrix.shape

(3, 3)

In [46]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.zeros((4,10))+10 *4/100

array([[0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]])

In [52]:
np.linspace(1,100,10) #start, stop, numbers

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [53]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.random.rand(4,5) *20

array([[12.23306321,  0.1413261 ,  0.4612485 , 10.49549321,  7.99721943],
       [ 0.93331326, 19.47511038,  4.65542681,  1.81212869, 12.36772019],
       [ 7.64923983, 19.66461772,  9.33525786, 17.19880813, 13.60615077],
       [ 9.00998504,  0.26529922, 18.84403511, 11.26576436,  7.70833005]])

In [55]:
np.random.randn(5,5) #can be negetive

array([[ 0.77919263, -1.10109776,  1.13022819,  0.37311891, -0.38647295],
       [-1.15877024,  0.56611283, -0.70445345, -1.3779393 , -0.35311665],
       [-0.46146572,  0.06665728, -0.17628566,  1.20089277,  0.69839894],
       [-0.17162884, -0.90718658,  1.18862573,  0.78553212,  2.65601009],
       [ 0.26348604,  1.64177112,  0.4608163 ,  0.08592347, -1.50995728]])

In [56]:
np.random.randint(1,100,10)

array([29, 15, 45, 65, 89, 71,  9, 88,  1,  8])

In [57]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [58]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
randArr = np.random.randint(0,50,10)
randArr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [60]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
randArr.max()

39

In [62]:
randArr.min()

2

In [63]:
randArr.argmax() #index

7

In [64]:
randArr.argmin()

9

In [65]:
randArr.dtype

dtype('int32')