In [4]:
import torch
import numpy as np

In [5]:
torch.__version__

'1.9.1+cpu'

In [6]:
np_array = np.array([1,2,3,4,5])

In [8]:
print(np_array)

[1 2 3 4 5]


In [9]:
np_array.dtype

dtype('int32')

In [12]:
x = torch.from_numpy(np_array)
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
torch.as_tensor(np_array)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [22]:
arr = np.arange(0.0,12.0)
arr_2d = arr.reshape(4,3)
arr_2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [26]:
x2 = torch.from_numpy(arr_2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

# tensors created with np array are linked to the tensors

In [27]:
np_array[0] = 99
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

## if we want not linked

In [38]:
my_arr = np.arange(0,12).reshape(4,3)
u_tensor = torch.tensor(my_arr)

In [39]:
my_arr[0] = 191
u_tensor

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.int32)